# Generated by Django 4.2 on 2023-04-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('classroom', models.CharField(blank=True, max_length=30, null=True)),
                ('building', models.CharField(blank=True, max_length=60, null=True)),
                ('online', models.BooleanField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField()),
            ],
            options={
                'db_table': 'Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('friendly_number', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'Reservation',
                'managed': False,
            },
        ),
    ]
